### ISSUE TITLE
eliminate multi byte char from adoc

### ISSUE THREAD

**Issue by kinichiro** [KiCad/kicad-doc#166] opened 2015-09-27 06:04 UTC
IMHO, adoc should not use multi byte char
if it is able to express by single byte char.

I think these could be eliminated from adoc.
- multi byte dash (– -> -)
- multi byte single quotation (’ and ‘ -> ')
- multi byte double quotation (“ and ” -> ")

And I also think these could be permitted.
- →
- …
- °

I listed up the adoc lines containing multi byte char here.
https://gist.github.com/kinichiro/9f3919491644e6f0f76d

How do you think about this ?

Thanks

**Comment by nickoe** [comment] 2015-09-27 09:18
What is the reason for this, even though it is called asciidoc, it supports UTF-8. A2x just needs the lang attribute set.

**Comment by kinichiro** [comment] 2015-09-27 13:09
Because some multi byte char seems give a bad influence on some editor.

For example, editing eeschema_general_top_toolbar.adoc with vi.
You can see multi byte '-' is displayed '?'.
![multi_byte_1](https://cloud.githubusercontent.com/assets/4927823/10122927/18a9dd1e-6564-11e5-862a-6d19d279fa54.png)

Editing pcbnew_routing.adoc with vi.
You can see some '?', but they should be single white space.
![multi_byte_2](https://cloud.githubusercontent.com/assets/4927823/10122930/4f160d8c-6564-11e5-8e70-a36fdcb9efd5.png)

I don't mean all multi byte char should be eliminated.
But, I think we should not use it as far as possible for avoiding troubles.

**Comment by ciampix** [comment] 2015-09-27 18:30
I agree 100%.

**Comment by LordBlick** [comment] 2015-09-28 12:51
Tool should be reported as buggy, not using std utf8…

**Comment by nickoe** [comment] 2015-09-30 18:33
@kinichiro That is simply because your terminal or font does not support it properly, please use a proper environment. Something that supports UTF-8. But that part is indeed a bit funny, but the problem is that someone who wrote that has inserted non breaking space. If you inspect the positions with a hex editor you will see it as C2 A0 in the pcbnew doc. And an en dash in the eeschema doc.

I suspect theese codes actually appeared from the odt to adoc conversion.

I think it does not hurt keeping them, but I guess it wont really hurt ot fix them either. if you feel like fixing these, I am ok with accepting a pull request on this.

I guess using the non multibyte chars for theese special chars will make it easier to debug if we find funky build errors too. But the last part is only a suspicion.

**Comment by kinichiro** [comment] 2015-10-03 13:59
@nickoe 
>I suspect theese codes actually appeared from the odt to adoc conversion.
I think so, too.
And I would like to remove unneeded multi byte chars as far as I can for avoiding unexpected trouble.

**Comment by nickoe** [comment] 2015-10-03 16:30
I will just close this since some commits to address this issue has been merged.

**Closed by nickoe** 2015-10-03 16:30 UTC

**Comment by ciampix** [comment] 2015-10-03 16:32
Thanks @nickoe
